### ISSUE TITLE
Kollaboration

### ISSUE THREAD

**Issue by ROBdk97** [rjcncpt/StarCitizen-Deutsch-INI#16]
Hey wollte darauf hinweisen das ich und viele andere auch an einer Deutschen Übersetzung in folgendem Repo gearbeitet haben:
https://github.com/Dymerz/StarCitizen-Localization

Wäre vorteilhaft wenn wir zusammenarbeiten würden und die Repos gegebenenfalls zusammenführen.
Das andere Repo dient dazu alle Sprachen unter einem Dach zusammen zu fürhen.

**Comment by rjcncpt** [comment]
Hallo. Danke für deinen Kommentar. Wir haben tatsächlich darüber nachgedacht. 

Unsere Idee ist folgende: Wir verfolgen langfristig einen ganz anderen Ansatz der Übersetzung und wissen nicht, wie es mit eurer Übersetzung harmoniert. Wir planen in den nächsten Veröffentlichungen keine 1:1 Übersetzung sondern eine Mischung aus englischer Sprache (insb. Eigennamen) und eigene, für uns logischeren Übersetzungen. 

Die Übersetzungen werden noch einmal komplett händisch überarbeitet. Auch verfeinern/optimieren wir einige Übersetzungen weil es für den Spieler einfacher ist sie zu lesen und zu verstehen. Das müssen wir auch tun, weil einige Textflächen/Buttons nicht dynamisch in der Breite sind und die Wörter der deutschen Übersetzung viel zu lang sind.

Ebenso möchten wir die Ansprache für Spieler relevante Bereiche informell (Du) gespalten. Questgeber/Questnehmer werden wahrscheinlich formell (Sie) miteinander sprechen. Es wird also aller Voraussicht eine sehr große Abweichung geben.

Vielleicht schaffen wir es eine etwas andere von der Community erstellte Übersetzung zu liefern :)

Viele Grüße

**Comment by ROBdk97** [comment]
Hallo @rjcncpt,

vielen Dank für deine ausführliche Antwort. Es ist toll zu hören, dass ihr einen durchdachten Ansatz für die Übersetzung verfolgt, und ich verstehe eure Beweggründe dafür vollkommen.

Interessanterweise sind viele der von euch angesprochenen Punkte auch bei uns im Fokus. Wir haben tatsächlich auch bereits damit begonnen, versehentlich übersetzte Eigennamen zurück ins Englische zu bringen. Zusätzlich arbeiten wir daran, unsere Übersetzung der UI anzupassen, um Probleme mit Textbreiten und Platzierung zu vermeiden.

Auch das Thema Formellität haben wir in Angriff genommen und versuchen, die Ansprache je nach Kontext angemessen zu gestalten.

Ich denke, unsere Projekte könnten voneinander profitieren, wenn wir uns austauschen und ggf. zusammenarbeiten würden. Obwohl unsere Ansätze unterschiedlich sein mögen, könnten sie sich ergänzen und zu einem noch besseren Ergebnis führen.

Wäre es vielleicht möglich, dass wir uns zusammensetzen und darüber sprechen, wie eine mögliche Zusammenarbeit aussehen könnte?

Vielen Dank im Voraus und beste Grüße!
