### ISSUE TITLE
Schuss pro Minute

### ISSUE THREAD

**Issue by greluc** [rjcncpt/StarCitizen-Deutsch-INI#166]
### Wo tritt der Fehler auf?
Beschreibungen der Waffen (z.B. `item_Descksar_sniper_ballistic_01=`)

### Beschreibe den Fehler
Das englische "rpm" der Feuerrate wurde mit "U/min" übersetzt, müsste aber "Schuss pro Minute" sein.

### Erwartete Übersetzung
Schuss pro Minute

### Screenshots
<img width="1547" alt="image" src="https://github.com/rjcncpt/StarCitizen-Deutsch-INI/assets/3463303/d29713d6-a9b8-4194-8f7a-4019f6a7892d">

### Version
- Channel: PTU
- Version: 3.21.1
- Build: 8889500

### Kontext
Dient als To-Do für @greluc

**Comment by rjcncpt** [comment]
Hm. Also s/min? Aber ist das denn geläufig so? Oder soll U/min zurück zu RPM?
