### ISSUE TITLE
Änderung durch SC Launcher Configurator

### ISSUE THREAD

**Issue by Aiden-Brice** [rjcncpt/StarCitizen-Deutsch-INI#34]
Hallo,
Bei "SC Launcher Configurator" gibt es in der aktuellen Version die Möglichkeit Konfigurationen wie FPS, VSync, Display_info_Level voreinzustellen.
Dabei wird die User.cfg umgeschrieben und der Language-Eintrag gelöscht. -ZACK, its english again ;)

===========================
Ich habe Zeitgleich auch auf Luftwerft angefragt ob man die Sprache nicht auch als Auswahlfeld einfügen kann.
- Und da könnte man ja sogar dann die aktuelle Sprache installieren lassen *zwinker* :D

**Comment by Asaya87** [comment]
Wir sind diesbezüglich bereits miteinander im Kontakt und suchen Lösungen

**Comment by rjcncpt** [comment]
Hallo @Aiden-Brice 
Danke für deinen Issue. Deine Idee ist wirklich super. Wäre mega wenn du den Entwickler mal etwas anstuppst :)

Viele Grüße
