### ISSUE TITLE
Vorgeschlagene Verbesserungen

### ISSUE THREAD

**Issue by greluc** [rjcncpt/StarCitizen-Deutsch-INI#395]
![image](https://github.com/rjcncpt/StarCitizen-Deutsch-INI/assets/76116052/1c1234e8-e78c-40dd-996e-e39bb5d49304)
2 weitere Kleinigkeiten gefunden.
Bekommt man ggf. über folgende Regex-Prüfung die Satzanfänge sinnvoll groß?

Ist Orision wirklich eine schwimmende und keine fliegende/schwebende Stadt?
=.*[:punct:]\s+[a-z]

_Originally posted by @Linebeck0 in https://github.com/rjcncpt/StarCitizen-Deutsch-INI/discussions/386#discussioncomment-8022427_

**Comment by rjcncpt** [comment]
Ich füge es meinem offenen PR hinzu
