### ISSUE TITLE
Weitere Übersetzungsfehler Mining

### ISSUE THREAD

**Issue by Linebeck0** [rjcncpt/StarCitizen-Deutsch-INI#399]
Vielen Dank für eure Anpassungen, ich hab leider die nächsten Kleinigkeiten gefunden, diesmal wieder im Kontext Mining.
Schwierigkeitsgrad "Hart" als "Fest"
Erze teilweise als "Erz", teilweise als Raw - Dann bitte alles gleich ;-)
![image](https://github.com/rjcncpt/StarCitizen-Deutsch-INI/assets/76116052/bc35219d-f699-47e7-a12e-8d1d7d3ed361)

Ist es euch eig. lieber das als Diskusion zu haben oder soll ich euch da jeweils Issues draus machen?

_Originally posted by @Linebeck0 in https://github.com/rjcncpt/StarCitizen-Deutsch-INI/discussions/386#discussioncomment-8026306_

Nachtrag: "ALARM: Kolisionsalarm" klingt auch doppelt. 
Macht da doch lieber eins der folgenden draus.
- Alarm: Kolisionsgefahrt
- Warnung: Kolisionsalarm

Danke vorab :-).

**Comment by rjcncpt** [comment]
> Schwierigkeitsgrad "Hart" als "Fest"
Erledigt


> Erze teilweise als "Erz", teilweise als Raw - Dann bitte alles gleich ;-)
Hast du Beispiele? Ich meine, Raw sind noch keine Erze sondern eben rohes Gestein. Das gibt CIG auch so an in ihrer engl. ini Datei.


> * Alarm: Kolisionsgefahrt
Klingt fantastisch :)


> Ist es euch eig. lieber das als Diskusion zu haben oder soll ich euch da jeweils Issues draus machen?
Das ist eigentlich egal. So wie du es lieber hast. Bei Diskussionen dann aber eine neue eröffnen, weil wenn sie einmal geschlossen ist, sehe ich nicht ob es Ergänzungen gibt. Ich bin jemand der alle Benachrichtigungen auf Stumm stelt :D 


Danke dir für deine Einreichungen.

**Comment by rjcncpt** [comment]
Dann hättest du Interesse wenn ich dich zu einem Contributor mache? Dann hättest du hier Zugriff auf die Pull Requests und könntest eigene PRs erstellen. Sofern du dich damit auskennst :)

**Comment by Linebeck0** [comment]
> > Schwierigkeitsgrad "Hart" als "Fest"
> 
> Erledigt
> 
Danke fürs übernehmen
> > Erze teilweise als "Erz", teilweise als Raw - Dann bitte alles gleich ;-)
> 
> Hast du Beispiele? Ich meine, Raw sind noch keine Erze sondern eben rohes Gestein. Das gibt CIG auch so an in ihrer engl. ini Datei.

Deswegen habe ich ein Bild mitgeliefert gehabt ... 

> > * Alarm: Kolisionsgefahrt
> 
> Klingt fantastisch :)

Danke fürs übernehmen

> > Ist es euch eig. lieber das als Diskusion zu haben oder soll ich euch da jeweils Issues draus machen?
> 
> Das ist eigentlich egal. So wie du es lieber hast. Bei Diskussionen dann aber eine neue eröffnen, weil wenn sie einmal geschlossen ist, sehe ich nicht ob es Ergänzungen gibt. Ich bin jemand der alle Benachrichtigungen auf Stumm stelt :D
> 
> Danke dir für deine Einreichungen.



> Dann hättest du Interesse wenn ich dich zu einem Contributor mache? Dann hättest du hier Zugriff auf die Pull Requests und könntest eigene PRs erstellen. Sofern du dich damit auskennst :)

Ich hab selbst bisher Git nur ohne Pull Requests verwendet und daher davon keine Ahnung. Ausserdem ist es sehr angenehm einfach Screenshots von Übersetzungsfehlern reinzusetzen und zu sagen "gug mal, so klingt das besser".
Wobei ich auch so ehrlich bin das ich natürlich den Fokus auf das lege, was ich aktiv in meinem Gameplay sehe - wie z.B. vorhin bei meiner Miningtour die Geschichten mit dem Kolisionsalarm, Schwierigkeitsgrad und den Erz-Benahmungen.

Ich bin auch so ehrlich, bei manchen Missionstexten gebt ihr euch richtig Mühe und baut schöne Fließtexte ... zum Beispiel bei den Risky Hammerhead-Missionen. Mir würde es persöhnlich genügen wenn da der Ort und die Info der Laufzeit steht. so muss man immer im Text schauen. Aber gut, das ist ja auch der Sinn der Sache.

Aber ja, kannst mir gerne die Berechtigungen geben, dann kann ich, wenn ich was sehe, dies als Issue hier reinstellen und wenn ich es selber finde es anpassen und als PR wem anders zum Rüberlesen geben.

Ansonsten zur Allgemeinen Einstellung: Ich sehe  das so, dass man möglichst gute Texte hinbekommen sollte, egal ob CIG sich orginal da was gutes oder weniger gutes Ausgedacht hat. Wenn die deutsche Übersetzung am ende besser ist wie das Englische Orgianl, finde ich das nicht wirklich schlimm ;-). 

Gruß

**Comment by rjcncpt** [comment]
Hehe, alles gut. Hab dir eine Einladung geschickt. Mach einfach wie du denkst. Deine Vorschläge sind bisher legitim und sinnvoll. Das mit den Texten, da stimme ich dir absolut zu. Der Fokus liegt erst einmal auf das was man offensichtlich sieht und dann gehts tiefer in die Texte. Zum Beispiel Missionen die der absolute Neueinsteiger zu 100% spielt. Solche Sachen haben aktuell den Fokus.

> Deswegen habe ich ein Bild mitgeliefert gehabt ...

Ach, dass hab ich gar nicht gesehen in deinem Screenshot. Aber ja, dass müsste so stimmen.

Danke dir :)
