### ISSUE TITLE
Diverse Übersetzungsfehler

### ISSUE THREAD

**Issue by PhanZero** [rjcncpt/StarCitizen-Deutsch-INI#4]
1. "new" wird übersetzt als "neues", was durch die Wandlung von "ue" zu "ü" zu einem "neüs" wird
2. folgend aus (1): Aus "New Babbage" wird in der INI "Neüs Babbage"
3. "Vulture" wird mehrmals, etwa bei den Paints, als "Geier" übersetzt (Vorsicht: Einzelne Parts verwenden korrekterweise den Begriff "Geier", muss also ein Mensch korrigieren!)
4. folgend aus (3): Einmal heißt die Vulture "Drake Interplanetarer Geier"

**Comment by PhanZero** [comment]
TrüDef = TruDef
\n = Zeilenvorschub
Anhänge = Aufsätze
ANhänge SEPERAT VERKAUFT! = Aufsätze SEPERAT ERHÄLTLICH!
Traktorbalkenbefestigung = Traktorstrahl-Aufsatz

**Comment by MaxM1211** [comment]
Ich bin an deinen Comments dran (falls von Pyro und Co. gewünscht mach ich dann die PR dafür auf)

**Comment by SC-C0** [comment]
Habe noch weiteres gefunden wie:
Variationen von 'oü' und 'eö' -> 'oeu' und 'eoe':
* Silhoütte -> Silhouette
* Schiffssilhoütte analog...
* Videöintrag -> Videoeintrag
* Geöntwicklungsunternehmen -> Geoentwicklungsunternehmen

Wie von [PhanZero](https://github.com/PhanZero) beschrieben die Variationen von 'eü' -> 'eue'
* Neün -> Neuen
* Neü analog...

**Comment by MaxM1211** [comment]
Jop die ö ü ä Dinger hab ich mit drin :-)
2. Kommentar kommt jzt :-D

**Comment by SC-C0** [comment]
Ich weis nicht ob es ein Unterschied zwischen den Zeichen „“ und " " gibt.. aber im Englischen wird zum Beispiel anstelle „Ghost“ -> "Ghost" geschrieben.

**Comment by SC-C0** [comment]
Die zu Substituierenden Wörter (also die Label-Parameter links des = Zeichens) sind noch teils falsch.. Beispiel:
....Queue..=Warteschlange 
wurde durch die Automatisierung zu 
...Qüü...=Warteschlange
übersetzt. Man findet sie Leicht mit regulärer Sprache: 
`.*(ü).*(=)
`

**Comment by SC-C0** [comment]
Für die Bugreports wäre es Vielleicht nicht schlecht den Original-Englischen namen bei den Missionen mit bei stehen zu haben:
![grafik](https://github.com/rjcncpt/StarCitizen-Deutsch-INI/assets/147988629/84ee56e8-b762-46be-8dee-39e14fa5f6f2)

Beispiel mit zeilenumbruch:
![grafik](https://github.com/rjcncpt/StarCitizen-Deutsch-INI/assets/147988629/1f903994-b804-4aee-8e7f-1a20459ff46e)
