### ISSUE TITLE
Korrekturen - Anzahl Klammern fehlerhaft

### ISSUE THREAD

**Issue by Linebeck0** [rjcncpt/StarCitizen-Deutsch-INI#406]
Es gibt Texte wo mehr Klammer-Zu wie Klammer auf vorhanden sind.
Betroffen sind aktuell folgende Zeilennummern
- 4506
- 36257
- 41059
- 43963
- 43964
- 44734
- 44735
- 45119
- 46045
- 46080
- 46600
- 46637
- 58423
- 59633
- 60032
- 60222
- 60312
- 60315

An mindestens einer Stelle (36257) ist das auch korrekt - das Python-Skript zum Prüfen anbei. Ggf. mit als Test implementieren?
[test.py](https://github.com/rjcncpt/StarCitizen-Deutsch-INI/files/13854576/test.txt)

**Comment by Linebeck0** [comment]
Die folgenden Zeilen sind Ok ohne anpassung. Müsste man ggf. mit in der Prüfung berücksichtigen
36257 a), b)-Aufzählung
44734 Tastaturbelegung
44735 Tastaturbelegung
46600 Tastaturbelegung
46637 Tastaturbelegung
60315 (Smilie)

Bei folgenden Zeilen bräuchte ich unterstützung
43963 
45119 (Was soll der folgende Satz bedeuten?) "Es sei denn, Sie melden Ihr gestohlenes Vehikel den Strafverfolgungsbehörden (dies kann problemlos bei einer Strafverfolgungsbehörde erfolgen). Vehikel-Terminal) gelten Sie immer noch als rechtmäßiger Eigentümer des Schiffes und sind für bestimmte von ihm begangene Straftaten verantwortlich."
46045 .... Hilfe, großer Missionstext, das darf sich gerne wer anders anschauen ;-)

**Comment by rjcncpt** [comment]
Also 43963 ist wie in deinem PR in Ordnung. 

Folgendes kannst du in deinem PR gern ersetzen.
`fine_terminal_informationScreen_Info=`
(dies kann problemlos bei einer Strafverfolgungsbehörde erfolgen) -> (Das kann problemlos an einem Terminal erledigt werden.)
