### ISSUE TITLE
Fehler in der Übersetzung beim ändern der Grafikeinstellungen (EPTU3.23)

### ISSUE THREAD

**Issue by ts-ws** [rjcncpt/StarCitizen-Deutsch-INI#525]
Hi,

beim ändern der Grafikeinstellungen bekommt man die Meldung das die Tastaturbelegung angewendet wird, und nicht die Grafikeinstellungen. :)

![2024-04-13 (1)](https://github.com/rjcncpt/StarCitizen-Deutsch-INI/assets/52138452/72bb1ac1-4404-4ea2-8e3b-d208715fcef7)
![2024-04-13 (2)](https://github.com/rjcncpt/StarCitizen-Deutsch-INI/assets/52138452/816f129a-cf85-4866-af5b-4168560804c9)

**Comment by rjcncpt** [comment]
Hehe. Alles klar. Ich schau mir das mal an. Danke dir!
