### ISSUE TITLE
imaging services = Visualisierungsdienste

### ISSUE THREAD

**Issue by qdsmm** [rjcncpt/StarCitizen-Deutsch-INI#546]
Versucht mal den imaging services als Visualisierungsdienste. Ergibt das da Sinn?

**Comment by rjcncpt** [comment]
Hey, dass klingt gut. Mal abwarten was die anderen sagen, dann würde ich das so übernehmen

Danke!

**Comment by MaxM1211** [comment]
Vorschläge:
bildgebenden Diagnostik
Bildgebungsabteilung

**Comment by qdsmm** [comment]
Freut mich das ich helfen konnte. Danke für euren Einsatz. Freue mich schon wieder mal mit Star Citizen anzufangen.

**Comment by rjcncpt** [comment]
> Ich hab mal kurz geschaut. Alle Sätze mit imaging services sind KH bezogen. Visualisierungsdienste hört sich für mich zu technisch an. Ich würde es etwas umschreiben und in Richtung Röntgengerät, bildgebende Verfahren drücken, was einfach medizinisch korrekter wäre

Das betrifft auch nur die verhassten Untertitel oder?

**Comment by MaxM1211** [comment]
Exakt :-D Die funktionieren aber bei mir im Moment sowieso nicht ordentlich. Überall die @VariablenKauderwelsch

**Comment by MaxM1211** [comment]
> Freut mich das ich helfen konnte. Danke für euren Einsatz. Freue mich schon wieder mal mit Star Citizen anzufangen.

Dankeschön und sehr gerne, viel Spaß in SC ⭐

**Comment by rjcncpt** [comment]
> Exakt :-D Die funktionieren aber bei mir im Moment sowieso nicht ordentlich. Überall die @VariablenKauderwelsch

Magst das mal umbauen? Hab Männergrippe und muss mich mal hinlegen ^^
