### ISSUE TITLE
Key Prüfung für die englische Original ini deaktivieren?

### ISSUE THREAD

**Issue by rjcncpt** [rjcncpt/StarCitizen-Deutsch-INI#582]
Könnte man die Key-Prüfung für `/.github/en/live` deaktivieren? Die ist ja die Referrenzdatei.

![Screenshot 2024-09-13 024955](https://github.com/user-attachments/assets/ae037245-cf37-48f1-ba3f-7e1b4defe35c)

**Comment by MaxM1211** [comment]
Wenn man den Test deaktiviert (was der Vorschlag ist), kann man auch gleich einfach eine Text Datei ohne Tests und Reviews zur Verfügung stellen. Man muss ! prüfen welche keys in der originalen (angepassten) en/live Datei ist, ansonsten kann man nicht wissen was in der deutschen LIVE fehlt!

**Comment by MaxM1211** [comment]
Deswegen macht man alles auf einmal. In einem PR.

Wenn das aber so gemeint ist wie du es schreibst, klar, dann bin ich fine wenn wir das bis zum go live deaktivieren

**Comment by MaxM1211** [comment]
Den Titel, als auch die Beschreibung verstehe ich anders...


Wie auch immer ist deaktiviert 👍🏼  (für die paar Tage)

**Comment by MaxM1211** [comment]
Huch, Fehler meinerseits, hab grad alle Tests in meiner Rage deaktiviert :-D Also ist doch nicht deaktiviert 👎🏼

**Comment by MaxM1211** [comment]
Ich finde so ein "temporäres" Deaktivieren nicht gut. Vorallem haben wir jetzt auch schon den Fall gehabt, dass jemand vorschnell das auch direkt schon aufs Live commited hat, und wenn jetzt keine Liveries mehr dazugekommen wären, hätten wir auch nur die global.ini angepasst, ohne den live anzupassen. Ich würde eher an die Ursache gehen, und die neue Referenz Datei halt erst hochladen wenn sie auch wirklich live ist. Das ist in meinen Augen durchaus vertretbar 👀

**Comment by MaxM1211** [comment]
Klar, der Eng Datei ist es egal ob sie mit einer anderen Datei verglichen wird oder nicht. Aber sich den Aufwand zumachen so eine Testumgehung zu schreiben halte ich für unnötig, da man das "normalerweise" mit der passenden Übersetzung oder per PR sowieso gleichzeitig pusht. 
Wenn ihr das notwendig findet, macht das. MMn macht das kein Sinn.

**Comment by rjcncpt** [comment]
Also noch mal von mir so wie ich es meinte.

Wenn man die englische original global.ini Datei aufspielt, soll diese keiner Prüfung unterliegen. Warum auch, das ist ja die Referenzdatei. Manchmal, wie in diesem Fall habe ich das schon vorbereitet, wenn das der RC sein wird. Bin ja am WE oft nicht daheim und müsste dann nicht 3 Commits (eng orig, live, ptu) erstellen sondern höchstens nur 2 (live, ptu). So lang wie keine Zeilen fehlen, kann man das schon mal machen.

**Comment by MaxM1211** [comment]
Eine Überprüfung der geänderten Datei(en) wäre nicht den Aufwand Wert.
