### ISSUE TITLE
Fehler in der Übersetzung beim Hinweistext zum Krankenbett

### ISSUE THREAD

**Issue by ChrisLetti** [rjcncpt/StarCitizen-Deutsch-INI#586]
### Wo tritt der Fehler auf?
Hinweistext zum Krankenbett

### Beschreibe den Fehler
Das Krankenbett hat deine Gesundheit wiederhergestellt und deinen BMS zurückgesetzt. Verwende die Registerkarte "Behandlung", um Verletzungen zu heilen (je nach Stufe). Die Registerkarte "Medikamente" dient zur dosierung der Medikation.

### Erwartete Übersetzung
Das Krankenbett hat deine Gesundheit wiederhergestellt und deinen BMS zurückgesetzt. Verwende die Registerkarte "Behandlung", um Verletzungen zu heilen (je nach Stufe). Die Registerkarte "Medikamente" dient zur Dosierung der Medikation.

### Version
- Channel: [LIVE, PTU]
- Version: [3.24.1 und 3.24.2]

### Zusätzlicher Kontext
Das Wort Dosierung schreibt man mit großem D. Zu finden in der Datei unter "Hints_ActorStatusMedBedEnter"

**Comment by rjcncpt** [comment]
Hey. Hast du es ingame getestet? Wegen Platz. Oft ist der Text dann zu lang. 

Grüße und danke!

**Comment by ChrisLetti** [comment]
Ich schau mal. Habs mal geändert. Wenn es wieder erscheint, mache ich mal einen Screenshot.

**Comment by ChrisLetti** [comment]
![ScreenShot-2024-10-07_11-48-37-AE9](https://github.com/user-attachments/assets/49a76b91-ac5f-4be4-b898-97a48f9f159a)

Man kann das problemlos ändern. Sollte auf dem Live dann auch funktionieren.

**Comment by rjcncpt** [comment]
> Man kann das problemlos ändern. Sollte auf dem Live dann auch funktionieren.

Sehr schön. Füge ich hinzu :)

**Comment by rjcncpt** [comment]
Ach sorry, ich dachte (je nach Stufe) wäre neu xD Jetzt sehe ich das es um "Dosierung" ging

**Comment by ChrisLetti** [comment]
Alles gut, kein Problem. Irren ist bekanntlich menschlich.
