### ISSUE TITLE
Fehlerhafte Übersetzung

### ISSUE THREAD

**Issue by ChrisLetti** [rjcncpt/StarCitizen-Deutsch-INI#599]
### Wo tritt der Fehler auf?
Reparatur eines Vehikles

### Beschreibe den Fehler
Reparatur - Rumpfreperatur
REPERATUR LÄUFT - NICHT ABHEBEN!

### Erwartete Übersetzung
Reparatur - Rumpfreparatur
REPARATUR LÄUFT - NICHT ABHEBEN!

### Screenshots
Wenn möglich, füge Screenshots ein, damit wir den Fehler direkt sehen und einordnen können.

### Version
- Channel: LIVE
- Version: 3.24.2a

### Zusätzlicher Kontext
Mir ist das beim reparieren eines Vehikles aufgefallen, dass das Wort Reparatur falsch geschrieben ist. Beim überprüfen der global.ini ist mir dann noch ein 2. Reparatur aufgefallen.

**Comment by MaxM1211** [comment]
Super gesehen ^^ Danke dir :-D Wird wahrscheinlich mit der 3.24.3 Live gehen 👍🏼

**Comment by rjcncpt** [comment]
Vielen Dank für deinen Report. Super gesehen :)
