### ISSUE TITLE
Vorschlag für Titel teils in englisch lassen

### ISSUE THREAD

**Issue by SC-C0** [rjcncpt/StarCitizen-Deutsch-INI#6]
Knebel wollte ggf die Auftragstitel in englisch haben.. das lässt sich ja einfach mit \n lösen.

mobiglas_ui_Investigation=Investigation\nUntersuchung
mobiglas_ui_Maintenance=Maintenance\nWartung
mobiglas_ui_Mercenary=Mercenary\nSöldner
mobiglas_ui_Mining=Mining\nBergbau
mobiglas_ui_Priority=Priority\nPriorität
mobiglas_ui_Race=Racing\nRennen

![grafik](https://github.com/rjcncpt/StarCitizen-Deutsch-INI/assets/147988629/a489f87e-e5e0-4a5b-8112-d96c588aa37b)

Achtung.. das ist nur schnell dahingeschmiert um das vorgehen allgemein zu erläutern,.. daher unvollständig, wie es auf dem Screenshot zu sehen ist.

so auch analog #todo
![grafik](https://github.com/rjcncpt/StarCitizen-Deutsch-INI/assets/147988629/5831cc6a-374f-4812-b5ac-6dbe0e1bea48)

**Comment by rjcncpt** [comment]
Hey @SC-C0 Sorry für die mega späte Antwort. Es kommt immer wieder etwas rein und dann ist man abgelenkt :D 

Deine Idee ist grundsätzlich echt geil und wir haben das mal ausprobiert. Das Problem ist nur die Optik. CIG müsste den Text in ein `vertical-align: middle;` o. ä. bringen. Aber so stört es uns irgendwie mehr.

Viele Grüße

**Comment by SC-C0** [comment]
Alles klar. Mir persönlich ist die deutsche übersetzung parallel dazu viel lieber. Werde es also zum gegebenen Zeitpunkt überarbeiten :)
