### ISSUE TITLE
In der Übersetzung sind die Anzeige der zu drückenden Taste für notification prompts hardgecoded

### ISSUE THREAD

**Issue by electron0** [rjcncpt/StarCitizen-Deutsch-INI#60]
Bei notification_prompt_accept, notification_prompt_decline und notification_prompt_dismiss darf das %s nicht einfach durch die ingame Taste ersetzt werden, das übernimmt das Spiel.

**Comment by rjcncpt** [comment]
Ja ich weiß. Aber es gibt kein Keybind dafür, oder?

**Comment by rjcncpt** [comment]
Jo. Aber geht nicht. Daher lassen wir das so lange drin bis CIG den Bug fixt. Stört ja niemanden und lässt sich nicht anders vorläufig fixen.

**Comment by electron0** [comment]
Das ist kein Bug seitens CIG dei Tasten müssen einfach übersetzt werden. Es gibt unterschiede in der dt. zu der amerikanischen Tastatur. (versuch doch mal die [ mit nur einer Taste zu erzeugen)
Klar man könnte sagen, die haben das Feature noch nciht eingebaut, dass man die Tasten umbelegen kann, aber das ändert nichts daran, dass die Tasten anders heißen als bei uns in Dtl.

**Comment by MaxM1211** [comment]
Ist jetzt mit Variablen wieder
