### ISSUE TITLE
Übersetzungsfehler für Recyceltes Material

### ISSUE THREAD

**Issue by DanielMKay** [rjcncpt/StarCitizen-Deutsch-INI#609]
### Wo tritt der Fehler auf?
Interaktionen & Terminal (Drake Vulture & TDD)

### Beschreibe den Fehler
items_commodities_type_RMV
items_commodities_type_RMV_desc

### Erwartete Übersetzung
items_commodities_type_RMC
items_commodities_type_RMC_desc

### Version
- Channel: LIVE
- Version: 3.24.3

**Comment by rjcncpt** [comment]
Hallo. Danke für die Meldung. Habe ich soeben korrigiert 👍🏻 

Viele Grüße
