### ISSUE TITLE
Waffen-Typ vereinheitlichen

### ISSUE THREAD

**Issue by greluc** [rjcncpt/StarCitizen-Deutsch-INI#611]
Vereinheitlichung der Bezeichnung des Waffen-Typs.
Momentan haben wir eine Mischung aus Deutsch, Englisch und Deutsch/Englisch.

Wenn niemand dagegen ist, werde ich die Typen Stück für Stück auf rein Deutsch umstellen.

**Comment by rjcncpt** [comment]
> Vereinheitlichung der Bezeichnung des Waffen-Typs. Momentan haben wir eine Mischung aus Deutsch, Englisch und Deutsch/Englisch.
> 
> Wenn niemand dagegen ist, werde ich die Typen Stück für Stück auf rein Deutsch umstellen.

Nicht rein Deutsch. Sind ja als Items zu bewerten. Die Deutsche Bezeichnung dahinter. Also `Power Plant / Generator` etc.

**Comment by rjcncpt** [comment]
Bezieht sich das wie im Titel nur auf Waffen oder auf alle Items?
Lass uns da absprechen. Heute kommt vielleicht erst mal ein neuer EPTU Patch. Da werde ich die neuen Zeilen übertragen. Du wolltest an WEs dran arbeiten oder?
